### ISSUE TITLE
【验收相关ISSUE】

### ISSUE THREAD

**Issue by huangjun12** [ELKYang/2s-AGCN-paddle#1]
1. 方便创建一个AIStudio项目吗，便于这边验收

**Comment by ELKYang** [comment]
> AIStudio地址https://aistudio.baidu.com/aistudio/projectdetail/3821064?contributionType=1&shared=1
请验收，谢谢

**Comment by ELKYang** [comment]
@huangjun12 AIStudio地址https://aistudio.baidu.com/aistudio/projectdetail/3821064?contributionType=1&shared=1
请验收，谢谢
