### ISSUE TITLE
您好，请问你知道怎么可视化文章中的邻接矩阵吗？

### ISSUE THREAD

**Issue by HeiHeiCCC** [ELKYang/2s-AGCN-paddle#2]
您好，请问你知道怎么可视化文章中学习到的的邻接矩阵吗？

**Comment by ELKYang** [comment]
把模型邻接矩阵的参数拿出来绘制一下就行

**Comment by ELKYang** [comment]
> 您好，请问你知道怎么可视化文章中学习到的的邻接矩阵吗？

把模型邻接矩阵的参数拿出来绘制一下就行

**Comment by HeiHeiCCC** [comment]
抱歉再次打扰，为什么我的顶层网络学习到的邻接矩阵，反而邻接信息没有了（纯黑白那个是一开始的邻接矩阵），但是准确率并没有下降啊？？&nbsp;&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月28日(星期天) 下午2:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ELKYang/2s-AGCN-paddle] 您好，请问你知道怎么可视化文章中的邻接矩阵吗？ (Issue #2)





  
您好，请问你知道怎么可视化文章中学习到的的邻接矩阵吗？
  
把模型邻接矩阵的参数拿出来绘制一下就行

**Comment by ELKYang** [comment]
> 抱歉再次打扰，为什么我的顶层网络学习到的邻接矩阵，反而邻接信息没有了（纯黑白那个是一开始的邻接矩阵），但是准确率并没有下降啊？？&nbsp;&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年5月28日(星期天) 下午2:15 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [ELKYang/2s-AGCN-paddle] 您好，请问你知道怎么可视化文章中的邻接矩阵吗？ (Issue #2) 您好，请问你知道怎么可视化文章中学习到的的邻接矩阵吗？ 把模型邻接矩阵的参数拿出来绘制一下就行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

邻接信息没有了什么意思？是矩阵拿出来没有值吗？

**Comment by HeiHeiCCC** [comment]
可能图片没有发过去，能加个微信吗？这是我的whdwx183




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月28日(星期天) 下午3:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ELKYang/2s-AGCN-paddle] 您好，请问你知道怎么可视化文章中的邻接矩阵吗？ (Issue #2)





  
抱歉再次打扰，为什么我的顶层网络学习到的邻接矩阵，反而邻接信息没有了（纯黑白那个是一开始的邻接矩阵），但是准确率并没有下降啊？？&nbsp;&nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年5月28日(星期天) 下午2:15 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [ELKYang/2s-AGCN-paddle] 您好，请问你知道怎么可视化文章中的邻接矩阵吗？ (Issue #2) 您好，请问你知道怎么可视化文章中学习到的的邻接矩阵吗？ 把模型邻接矩阵的参数拿出来绘制一下就行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
邻接信息没有了什么意思？是矩阵拿出来没有值吗？

**Comment by yyc3215** [comment]
> 您好，请问你知道怎么可视化文章中学习到的的邻接矩阵吗？

请问你解决了这个问题吗？

**Comment by HeiHeiCCC** [comment]
应该是解决了，做法就是你训练完之后找到最高正确率的权重文件，然后使用torch.load加载它（你可以看看他的形式），然后找你需要的那一层就行：

例如需要找第一层的邻接矩阵：

weights = torch.load(XXX)

plt.imshow(weights["l1.gcn1.PA"])

我是这样子做的（不知道对不对，因为出来的结果跟论文里感觉是相反的，有点迷），有其他办法可以一起交流噢







HeiHei
***@***.***







                       
原始邮件
                       
                     

发件人："yyc3215"< ***@***.*** &gt;;

发件时间：2023/12/18 21:18

收件人："ELKYang/2s-AGCN-paddle"< ***@***.*** &gt;;

抄送人："HeiHeiCCC"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [ELKYang/2s-AGCN-paddle] 您好，请问你知道怎么可视化文章中的邻接矩阵吗？ (Issue #2)




  
您好，请问你知道怎么可视化文章中学习到的的邻接矩阵吗？
  
请问你解决了这个问题吗？

**Comment by yyc3215** [comment]
好的好的，谢谢你！我明天试试🫡

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月18日 21:30 |
| 收件人 | ELKYang/2s-AGCN-paddle ***@***.***> |
| 抄送人 | yyc3215 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [ELKYang/2s-AGCN-paddle] 您好，请问你知道怎么可视化文章中的邻接矩阵吗？ (Issue #2) |

应该是解决了，做法就是你训练完之后找到最高正确率的权重文件，然后使用torch.load加载它（你可以看看他的形式），然后找你需要的那一层就行：

例如需要找第一层的邻接矩阵：

weights = torch.load(XXX)

plt.imshow(weights["l1.gcn1.PA"])

我是这样子做的（不知道对不对，因为出来的结果跟论文里感觉是相反的，有点迷），有其他办法可以一起交流噢







HeiHei
***@***.***








原始邮件



发件人："yyc3215"< ***@***.*** &gt;;

发件时间：2023/12/18 21:18

收件人："ELKYang/2s-AGCN-paddle"< ***@***.*** &gt;;

抄送人："HeiHeiCCC"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [ELKYang/2s-AGCN-paddle] 您好，请问你知道怎么可视化文章中的邻接矩阵吗？ (Issue #2)





您好，请问你知道怎么可视化文章中学习到的的邻接矩阵吗？

请问你解决了这个问题吗？

**Comment by ELKYang** [comment]
> 应该是解决了，做法就是你训练完之后找到最高正确率的权重文件，然后使用torch.load加载它（你可以看看他的形式），然后找你需要的那一层就行： 例如需要找第一层的邻接矩阵： weights = torch.load(XXX) plt.imshow(weights["l1.gcn1.PA"]) 我是这样子做的（不知道对不对，因为出来的结果跟论文里感觉是相反的，有点迷），有其他办法可以一起交流噢 HeiHei ***@***.*** 原始邮件 发件人："yyc3215"< ***@***.*** &gt;; 发件时间：2023/12/18 21:18 收件人："ELKYang/2s-AGCN-paddle"< ***@***.*** &gt;; 抄送人："HeiHeiCCC"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;; 主题：Re: [ELKYang/2s-AGCN-paddle] 您好，请问你知道怎么可视化文章中的邻接矩阵吗？ (Issue #2) 您好，请问你知道怎么可视化文章中学习到的的邻接矩阵吗？ 请问你解决了这个问题吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这样没问题，weights["l1.gcn1.PA"]只是其中一层GCN的图邻接矩阵，可以把10层的都拿出来看看
