### ISSUE TITLE
请问评价指标CS和CV分别怎么计算

### ISSUE THREAD

**Issue by Cagares** [ELKYang/2s-AGCN-paddle#3]

**Comment by ELKYang** [comment]
可以看这里，因为嵌套在了paddlevideo框架里面，可能不是那么清晰，实际上就是准确率ACC。对于CS和CV只是数据不同罢了https://github.com/ELKYang/2s-AGCN-paddle/blob/635080272ffa1ea47eb5b991568083bd2a2e0cd1/infer.py#L194

**Comment by Cagares** [comment]
麻烦请问xview数据集和xsub数据集具体有什么区别

**Comment by ELKYang** [comment]
2sAGCN文章中有说明，可以查阅

**Comment by Cagares** [comment]
好哒。我使用aagcn，在x-view的joint训练出的结果在94左右，但是在bone训练的结果很差，不到百分之八十(bitch_size=32，lr=0.2、0.1都试过)

**Comment by ELKYang** [comment]
2sAGCN文章中是joint和bone各训练分支网络在最后进行ensemble的，所以才称之为双流。建议详细阅读一下原文。

**Comment by Cagares** [comment]
我是这样做的，在bone的训练结果很差

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年09月18日 16:51 |
| 收件人 | ***@***.***> |
| 抄送人 | Cagares ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [ELKYang/2s-AGCN-paddle] 请问评价指标CS和CV分别怎么计算 (Issue #3) |

2sAGCN文章中是joint和bone各训练分支网络在最后进行ensemble的，所以才称之为双流。建议详细阅读一下原文。

**Comment by ELKYang** [comment]
这很正常的呀，单bone的效果肯定不如单joint，只是起辅助作用。
